produtos = [
    {'codigo': 1, 'nome': 'Introdução à Computação - Volume 1', 'tipo': 'ti', 'valor': 10.00},
    {'codigo': 2, 'nome': 'Introdução à Computação - Volume 2', 'tipo': 'ti', 'valor': 10.00},
    {'codigo': 3, 'nome': 'Linguagens de Programação Web', 'tipo': 'ti', 'valor': 10.00},
    {'codigo': 4, 'nome': 'Tecnologias de Scripting', 'tipo': 'ti', 'valor': 10.00},
    {'codigo': 5, 'nome': 'Desenvolvimento Web com SQL', 'tipo': 'ti', 'valor': 15.00},
    {'codigo': 6, 'nome': 'Desenvolvimento Web com C++', 'tipo': 'ti', 'valor': 15.00},
    {'codigo': 7, 'nome': 'Desenvolvimento Web com Java', 'tipo': 'ti', 'valor': 15.00},
    {'codigo': 8, 'nome': 'Desenvolvimento Web com .Net', 'tipo': 'ti', 'valor': 15.00},
    {'codigo': 9, 'nome': 'Hardware e Redes de Computadores - Volume 1', 'tipo': 'ti', 'valor': 15.00},
    {'codigo': 10, 'nome': 'Hardware e Redes de Computadores - Volume 2', 'tipo': 'ti', 'valor': 15.00},
    {'codigo': 11, 'nome': 'Hardware e Redes de Computadores - Volume 3', 'tipo': 'ti', 'valor': 15.00},
    {'codigo': 12, 'nome': 'Hardware e Redes de Computadores - Volume 4', 'tipo': 'ti', 'valor': 15.00},
    {'codigo': 13, 'nome': 'Dominando o Inglês', 'tipo': 'comunicação', 'valor': 5.00},
    {'codigo': 14, 'nome': 'Comunicação Empresarial', 'tipo': 'comunicação', 'valor': 10.00},
    {'codigo': 15, 'nome': 'Desenvolvimento Pessoal - Livro 1', 'tipo': 'auto-ajuda', 'valor': 15.00},
    {'codigo': 16, 'nome': 'Desenvolvimento Pessoal - Livro 2', 'tipo': 'auto-ajuda', 'valor': 15.00},
    {'codigo': 17, 'nome': 'Introdução à Computação - Volume 1', 'tipo': 'ti', 'valor': 10.00},
    {'codigo': 18, 'nome': 'Introdução à Computação - Volume 2', 'tipo': 'ti', 'valor': 10.00},
    {'codigo': 19, 'nome': 'Fundamentos da Programação', 'tipo': 'ti', 'valor': 12.00},
    {'codigo': 20, 'nome': 'Algoritmos e Estruturas de Dados',  'tipo': 'ti','valor': 15.00},
    {'codigo': 21, 'nome': 'Introdução à Engenharia de Software','tipo': 'ti', 'valor': 18.00},
    {'codigo': 22, 'nome': 'Banco de Dados', 'tipo': 'ti', 'valor': 12.00},
    {'codigo': 23, 'nome': 'Programação Web com Python', 'tipo': 'ti', 'valor': 15.00},
    {'codigo': 24, 'nome': 'Programação Web com JavaScript', 'tipo': 'ti', 'valor': 15.00},
    {'codigo': 25, 'nome': 'Introdução à Ciência da Computação', 'tipo': 'ti', 'valor': 18.00},
    {'codigo': 26, 'nome': 'Inteligência Artificial', 'tipo': 'ti', 'valor': 20.00},
    {'codigo': 27, 'nome': 'Redes de Computadores', 'tipo': 'ti', 'valor': 15.00},
    {'codigo': 28, 'nome': 'Segurança da Informação', 'tipo': 'ti', 'valor': 18.00},
    {'codigo': 29, 'nome': 'Administração de Sistemas', 'tipo': 'gestão', 'valor': 15.00},
    {'codigo': 30, 'nome': 'Gestão de Projetos de TI', 'tipo': 'gestão', 'valor': 12.00},
    {'codigo': 31, 'nome': 'Introdução à Estatística', 'tipo': 'ciências exatas', 'valor': 10.00},
    {'codigo': 32, 'nome': 'Probabilidade', 'tipo': 'ciências exatas', 'valor': 10.00},
    {'codigo': 33, 'nome': 'Matemática Discreta', 'tipo': 'ciências exatas', 'valor': 12.00},
    {'codigo': 34, 'nome': 'Cálculo', 'tipo': 'ciências exatas', 'valor': 15.00},
    {'codigo': 35, 'nome': 'Álgebra Linear', 'tipo': 'ciências exatas', 'valor': 12.00},
    {'codigo': 36, 'nome': 'Geometria Analítica', 'tipo': 'ciências exatas', 'valor': 10.00},
    {'codigo': 37, 'nome': 'Física', 'tipo': 'ciências exatas', 'valor': 15.00},
    {'codigo': 38, 'nome': 'Química', 'tipo': 'ciências exatas', 'valor': 12.00},
    {'codigo': 39, 'nome': 'Biologia', 'tipo': 'ciências exatas', 'valor': 10.00},
    {'codigo': 40, 'nome': 'História', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 41, 'nome': 'Geografia', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 42, 'nome': 'Sociologia', 'tipo': 'ciências humanas', 'valor': 12.00},
    {'codigo': 43, 'nome': 'Filosofia', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 44, 'nome': 'Literatura Brasileira', 'tipo': 'comunicação', 'valor': 10.00},
    {'codigo': 45, 'nome': 'Literatura Portuguesa', 'tipo': 'comunicação', 'valor': 10.00},
    {'codigo': 46, 'nome': 'Literatura Inglesa', 'tipo': 'comunicação', 'valor': 10.00},
    {'codigo': 47, 'nome': 'Literatura Espanhola', 'tipo': 'comunicação', 'valor': 10.00},
    {'codigo': 48, 'nome': 'Literatura Francesa', 'tipo': 'comunicação', 'valor': 10.00},
    {'codigo': 49, 'nome': 'Literatura Alemã', 'tipo': 'comunicação', 'valor': 10.00},
    {'codigo': 50, 'nome': 'Literatura Italiana', 'tipo': 'comunicação', 'valor': 10.00},
    {'codigo': 51, 'nome': 'Literatura Russa', 'tipo': 'comunicação', 'valor': 10.00},
    {'codigo': 52, 'nome': 'Literatura Japonesa', 'tipo': 'comunicação', 'valor': 10.00},
    {'codigo': 53, 'nome': 'Literatura Chinesa', 'tipo': 'comunicação', 'valor': 10.00},
    {'codigo': 54, 'nome': 'Arte', 'tipo': 'artes', 'valor': 10.00},
    {'codigo': 55, 'nome': 'Música', 'tipo': 'artes', 'valor': 10.00},
    {'codigo': 56, 'nome': 'Cinema', 'tipo': 'artes', 'valor': 10.00},
    {'codigo': 57, 'nome': 'Teatro', 'tipo': 'artes', 'valor': 10.00},
    {'codigo': 58, 'nome': 'Dança', 'tipo': 'artes', 'valor': 10.00},
    {'codigo': 59, 'nome': 'Fotografia', 'tipo': 'artes', 'valor': 10.00},
    {'codigo': 60, 'nome': 'Direito', 'tipo': 'ciências humanas', 'valor': 15.00},
    {'codigo': 61, 'nome': 'Economia', 'tipo': 'ciências exatas', 'valor': 12.00},
    {'codigo': 62, 'nome': 'Administração', 'tipo': 'gestão', 'valor': 10.00},
    {'codigo': 63, 'nome': 'Contabilidade', 'tipo': 'gestão', 'valor': 12.00},
    {'codigo': 64, 'nome': 'Marketing', 'tipo': 'comunicação', 'valor': 10.00},
    {'codigo': 65, 'nome': 'Publicidade e Propaganda', 'comunicação': 'ti', 'valor': 10.00},
    {'codigo': 66, 'nome': 'Recursos Humanos', 'tipo': 'gestão', 'valor': 10.00},
    {'codigo': 67, 'nome': 'Relações Públicas', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 68, 'nome': 'Comunicação', 'tipo': 'comunicação', 'valor': 10.00},
    {'codigo': 69, 'nome': 'Jornalismo', 'tipo': 'comunicação', 'valor': 12.00},
    {'codigo': 70, 'nome': 'Psicologia', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 71, 'nome': 'Sociologia', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 72, 'nome': 'Antropologia', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 73, 'nome': 'Ciência Política', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 74, 'nome': 'História da Arte', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 75, 'nome': 'História da Música', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 76, 'nome': 'História do Cinema', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 77, 'nome': 'História do Teatro', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 78, 'nome': 'História da Dança', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 79, 'nome': 'História da Fotografia', 'tipo': 'ciências humanas','valor': 10.00},
    {'codigo': 80, 'nome': 'Filosofia da Arte', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 81, 'nome': 'Filosofia da Música', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 82, 'nome': 'Filosofia do Cinema', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 83, 'nome': 'Filosofia do Teatro', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 84, 'nome': 'Filosofia da Dança', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 85, 'nome': 'Filosofia da Fotografia', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 86, 'nome': 'Ética', 'tipo': 'ciências humanas','valor': 10.00},
    {'codigo': 87, 'nome': 'Ética Profissional', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 88, 'nome': 'Ética e Responsabilidade Social', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 89, 'nome': 'Lógica para Alunos', 'tipo': 'ciências exatas', 'valor': 10.00},
    {'codigo': 90, 'nome': 'Pensamento Crítico', 'tipo': 'ciências humanas', 'valor': 10.00},
    {'codigo': 91, 'nome': 'Introdução ao Direito', 'tipo': 'ciências humanas', 'valor': 15.00},
    {'codigo': 92, 'nome': 'Direito Constitucional', 'tipo': 'ciências humanas', 'valor': 15.00},
    {'codigo': 93, 'nome': 'Direito Civil', 'tipo': 'ciências humanas', 'valor': 15.00},
    {'codigo': 94, 'nome': 'Direito Penal', 'tipo': 'ciências humanas', 'valor': 15.00},
    {'codigo': 95, 'nome': 'Direito Processual', 'tipo': 'ciências humanas', 'valor': 15.00},
    {'codigo': 96, 'nome': 'Direito do Trabalho', 'tipo': 'ciências humanas', 'valor': 15.00},
    {'codigo': 97, 'nome': 'Direito Tributário', 'tipo': 'ciências humanas', 'valor': 15.00},
    {'codigo': 98, 'nome': 'Direito Empresarial', 'tipo': 'ciências humanas', 'valor': 15.00},
    {'codigo': 99, 'nome': 'Direito Internacional', 'tipo': 'ciências humanas', 'valor': 15.00},
    {'codigo': 100, 'nome': 'Direito Ambiental', 'tipo': 'ciências humanas', 'valor': 15.00},
]

def calcula_total_desconto(compra):
    total = 0
    for produto in compra:
        total += (produto['valor'] * produto['quantidade'])
    desconto = 0

    if total >= 100:
        desconto = total * 0.1
        total *= 0.9

    return total, desconto